/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2015-09-14 13:03:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>FIX-PARSER</title>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/app.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".button {\n");
      out.write("\n");
      out.write("    /*Step 2: Basic Button Styles*/\n");
      out.write("    display: block;\n");
      out.write("    height: 50px;\n");
      out.write("    width: 150px;\n");
      out.write("    background: #34696f;\n");
      out.write("    border: 2px solid rgba(33, 68, 72, 0.59);\n");
      out.write("\n");
      out.write("    /*Step 3: Text Styles*/\n");
      out.write("    color: rgba(0, 0, 0, 0.55);\n");
      out.write("    text-align: center;\n");
      out.write("    font: bold 1.5em/50px \"Helvetica Neue\", Arial, Helvetica, Geneva, sans-serif;\n");
      out.write("\n");
      out.write("    /*Step 4: Fancy CSS3 Styles*/\n");
      out.write("    background: -webkit-linear-gradient(top, #34696f, #2f5f63);\n");
      out.write("    background: -moz-linear-gradient(top, #34696f, #2f5f63);\n");
      out.write("    background: -o-linear-gradient(top, #34696f, #2f5f63);\n");
      out.write("    background: -ms-linear-gradient(top, #34696f, #2f5f63);\n");
      out.write("    background: linear-gradient(top, #34696f, #2f5f63);\n");
      out.write("\n");
      out.write("    -webkit-border-radius: 50px;\n");
      out.write("    -khtml-border-radius: 50px;\n");
      out.write("    -moz-border-radius: 50px;\n");
      out.write("    border-radius: 50px;\n");
      out.write("\n");
      out.write("    -webkit-box-shadow: 0 8px 0 #1b383b;\n");
      out.write("    -moz-box-shadow: 0 8px 0 #1b383b;\n");
      out.write("    box-shadow: 0 8px 0 #1b383b;\n");
      out.write("\n");
      out.write("    text-shadow: 0 2px 2px rgba(255, 255, 255, 0.2);\n");
      out.write("\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center><font size=\"6\">FIX PARSER</font></center>\n");
      out.write("<center><textarea id=\"fixmsg\" rows=\"10\" cols=\"220\"></textarea></center>\n");
      out.write("<center><a id=\"parseLink\" href=\"#\" class=\"button\" onclick=\"loadXMLDoc();\">link text</a><center>\n");
      out.write("<br/><br/>\n");
      out.write("<textarea id = \"response\" rows=\"10\" cols=\"220\"></textarea>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
